############################################################
#
# Tomcat 配置 端口号用8088!!
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
  port: 8777
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:  # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodMart?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: root1234
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000 # 文件上传大小限制为500KB
      max-request-size: 512000 # 请求大小限制为500KB
  redis:
    database: 1   #database数量，16以内，默认是0
    host: 192.168.218.22   #我们所使用的Redis所在的主机地址，这虚拟机的，若是我们的本机那就是127.0.0.1
    port: 6379
    timeout: 500
    password: rlj
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.rlj.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.rlj.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
#分页插件配置
pagehelper:
  helperDialect: mysql            #告知我们所使用的数据库种类
  supportMethodsArguments: true   #允许开启一些pagehelper的配置
############################################################
#
# fastDFS 配置
#
############################################################
fdfs:
  connect-timeout: 3000  #连接的超时时间
  so-timeout: 3000       #读取的超时时间
  tracker-list: 192.168.218.3:22122  #tracker服务所在的IP与端口号